FROM ubuntu
MAINTAINER XueSeason

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update
RUN apt-get -y install curl

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 7.8.0

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install v$NODE_VERSION \
    && nvm alias default v$NODE_VERSION

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

COPY ./node-server-src /src

RUN cd /src; npm config set registry https://registry.npm.taobao.org; npm install --production
ENV EGG_SERVER_ENV prod
ENV NODE_ENV production

EXPOSE 7001

CMD ["node", "/src/app.js"]
